# Generated by Django 3.1.3 on 2022-06-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeNumber', models.CharField(max_length=255)),
                ('employeeName', models.CharField(max_length=255)),
                ('jobDescription', models.TextField()),
                ('employementDate', models.DateTimeField()),
                ('branch', models.CharField(max_length=50)),
            ],
        ),
    ]
