# Generated by Django 3.1.3 on 2022-06-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employementDate',
            field=models.CharField(default='10/06/2022', max_length=50),
        ),
    ]
